<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class calender extends Model
{
    use HasFactory;
    protected $table = 'calender';
    protected $fillable = [
        'id',
        'idu',
        'id_user',
        'user',       
        'n1',       
        'n2',       
        'n3',
        'n4',
        'n5',
        'n6',
        'n7',
        'n8',
        'n9',
        'n10',
        'n11',
        'n12',
        'n13',
        'n14',
        'n15',
        'n16',
        'n17',
        'n18',
        'n19',
        'n20',
        'n21',
        'n22',
        'n23',
        'n24',
        'n25',
        'n26',
        'n27',
        'n28',
        'n29',
        'n30',
        'n31',
        'c1',       
        'c2',       
        'c3',
        'c4',
        'c5',
        'c6',
        'c7',
        'c8',
        'c9',
        'c10',
        'c11',
        'c12',
        'c13',
        'c14',
        'c15',
        'c16',
        'c17',
        'c18',
        'c19',
        'c20',
        'c21',
        'c22',
        'c23',
        'c24',
        'c25',
        'c26',
        'c27',
        'c28',
        'c29',
        'c30',
        'c31',
        'timework',
        't1',
        't2',
        't3',
        't4',
        't5'
    ];
    public $timestamps = false;
}
